### ISSUE TITLE
Better filtering

### ISSUE THREAD

**Issue by MichaelGooden** [moneyphp/iso-currencies#1]
I have seen a few anomalies in the currency data created by this script.

## Problem
  - Countries in the source without a currency get added to the list with a blank array key, with the last country in the list overwriting all previous countries: https://github.com/moneyphp/iso-currencies/blob/master/resources/current.php#L58
  - Handling of `EUR`, `USD` and other currencies used by multiple countries. There are multiple countries in the list each claiming usage of `EUR` (as is expected). In the generated output however, these get overwritten similarly to the above issue with the last country claiming the EUR 'winning' in the list, in the current iteration, Spain: https://github.com/moneyphp/iso-currencies/blob/master/resources/current.php#L10
(The USD is also affected: https://github.com/moneyphp/iso-currencies/blob/master/resources/current.php#L34)

## Possible Solutions
  - Do not process entries from the source without a valid currency code. This solves the first problem.
  - Do not include country data. As the current implementations in [\Money\Currencies\ISOCurrencies](https://github.com/moneyphp/money/blob/master/src/Currencies/ISOCurrencies.php) does not use country data, this is an easy option. Alternatively;
  - Store country data separately. (Can a use case be made for it?)

**Comment by frederikbosch** [comment]
@MichaelGooden Good catches. I am in favour of all three offered solutions. Will implement them asap.

**Comment by MichaelGooden** [comment]
I do feel it would be nice to have the list of countries per currency, something like:
```php
return [
  'EUR' => 
  array (
    'alphabeticCode' => 'EUR',
    'currency' => 'Euro',
    'entities' => [
      'SPAIN',
      'GERMANY`,
      `FRANCE`,
    ],
    'minorUnit' => 2,
    'numericCode' => 978,
  ),
]
```

Except these are not ISO country codes, which makes this data useless in my opinion.

**Comment by MichaelGooden** [comment]
I think it is best to remove the country data completely, only leaving the directly currency-related information. Users can use the valid ISO currency code to retrieve further information from alternative sources.

**Comment by frederikbosch** [comment]
@MichaelGooden Let's go for a list without countries to be used inside `moneyphp/money`. I will create a separate list which includes the countries as proposed in your previous post.
