### ISSUE TITLE
Bump symfony/yaml version support

### ISSUE THREAD

**Issue by ammonkc** [moneyphp/iso-currencies#10]
I get composer dependency errors since I'm using symfony 4.3 components. Would you be able to bump up the dependency version to support symfony/yaml ^4.3 ?

**Comment by sagikazarmark** [comment]
@ammonkc do you know if it's backward compatible with symfony/yaml 3.x?

If it is, I'd accept a PR adding support for symfony 4.

If not, we will have to look into what needs to be changed.

**Comment by ammonkc** [comment]
Sorry, I don't know if it's backward compatible with 3.x

**Comment by frederikbosch** [comment]
Fixed, also tagged new version inlcuding new currency

**Comment by sagikazarmark** [comment]
Nice, thanks @frederikbosch
