### ISSUE TITLE
Easy way to access ISO Codes and currency names

### ISSUE THREAD

**Issue by itsDavidSQ** [moneyphp/iso-currencies#3]
On the app I am currently working we need to show a list of ISO codes and currency names. Since we are pulling in this package (through the use of `moneyphp/money`) and it already contains al data we need, it would be nice to expose it.

**Comment by frederikbosch** [comment]
```php
<?php
use Money\Currencies\ISOCurrencies;

$data = require 'vendor/moneyphp/money/resources/currency.php';

$currencies = new ISOCurrencies();
foreach ($currencies as $currency) {
  $name = $data[$currency]['currency'];
}
```

Above solution is correct direction, but might contain errors.
